# Generated by Django 5.2.1 on 2025-06-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoMuni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudretiro',
            name='fecha_completada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudretiro',
            name='estado',
            field=models.CharField(choices=[('C', 'Completada'), ('R', 'En ruta'), ('P', 'Pendiente')], default='P', max_length=1),
        ),
    ]
