# Generated by Django 5.2.1 on 2025-07-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='profesor',
            field=models.CharField(max_length=100),
        ),
    ]
